---

- name: wildfly cleanup jboss stop
  command: "{{wildfly_jboss_cmd}} stop"

- name: wildfly cleanup clear undeployed
  file:
    path: "{{wildfly_jboss_deploy_dir}}/{item}.undeployed"
    state: absent
  notify: wildfly cleanup clear lock
  with_items: "{{ wildfly_jboss_deploy_files }}"

- name: wildfly cleanup clear lock
  file:
    path: "{{wildfly_jboss_deploy_dir}}/migration.log.lck"
    state: absent

- name: wildfly cleanup jboss start
  command: "{{wildfly_jboss_cmd}} start"
  notify: wildfly cleanup jboss check

- name: wildfly cleanup jboss check
  wait_for: path="{{wildfly_waitfor_deploy}}" delay=10 timeout=90