---

- name: wildfly cleanup jboss stop
  command: "/usr/local/bin/jboss stop"

- name: wildfly cleanup clear undeployed
  shell: "rm *.undeployed migration.log.lck"
  args:
    chdir: "/home/jboss/wildfly-8/standalone/deployments"

- name: wildfly cleanup jboss start
  command: "/usr/local/bin/jboss start"
  notify: wildfly cleanup jboss check

- name: wildfly cleanup jboss check
  wait_for: path="/home/jboss/wildfly-8/standalone/deployments/oracle-ds.xml.deployed" delay=10 timeout=90